### PR TITLE
Products page

### PR DESCRIPTION
**Pull request by sudipkundu999**
In this PR -
- adding useAxios
- updating products price in DB to showcase the filters
- adding product context and reducer
- Functionality: filters to the product page
- Functionality: clicking on categories on the homepage it will take to the product page and show only that category

[Check these files only](https://github.com/sudipkundu999/CobraStore-React/pull/6/files?file-filters%5B%5D=.js&file-filters%5B%5D=.jsx&show-viewed-files=true)

Preview - 
PR-product-page

### CODE REVIEW

**Review by srishtigautam21 — APPROVED** [review]
The UI looks awesome
the functionality added works smoothly
The code is also clean and understandable
Good work good to merge

**Review by dev-prabhat — APPROVED** [review]
All good, no need to change code, like the reusability of useAxios hooks

**Review by abhishektanwar — APPROVED** [review]
Code is clean and understandable .
Suggestion : 

Currently when we click on category on home page ,we navigate to `/products` page and a param is provided which is category clicked and then we have to listen on products page if param is provided and set Filter . 

- What could be done is have initial state for products filter in `product context` and use `product reducer` to get the updated state of `filter object` and expose dispatch function of `product reducer` and `filter state` from `product context provider` . This way we wouldn't have to pass param from home page and a function could be directly dispatched to set category filter upon clicking category and navigate to `/products` page.

UI is great . Good work

**Comment by sudipkundu999** [comment]
> Code is clean and understandable . Suggestion :
> 
> Currently when we click on category on home page ,we navigate to `/products` page and a param is provided which is category clicked and then we have to listen on products page if param is provided and set Filter .
> 
> * What could be done is have initial state for products filter in `product context` and use `product reducer` to get the updated state of `filter object` and expose dispatch function of `product reducer` and `filter state` from `product context provider` . This way we wouldn't have to pass param from home page and a function could be directly dispatched to set category filter upon clicking category and navigate to `/products` page.
> 
> UI is great . Good work

Great suggestion. I will try to implement this. Also, this suggestion made me realize another mistake.
Thank you so much!

**Pull request merged**
